<script context="module">
    export const prerender = false;
</script>
<p>Peace has become an elusive dream for the whole world especially now that the world powers are scampering for world supremacy. Each powerful nation seems to have a secret nuclear arsenal that is on standby in case some other super country is prepared to expose its own nuclear power.</p>
<p>While people all over the world should be concerned about a third world war that will surely be swift considering the use of the nuclear arsenal of every powerful country, people however have to be prepared for something just brewing around the corner.</p>
<p>The risk of a civil war erupting in just about any country is an ever present risk that should be looked into not only by world leaders and the church but also by every person concerned about the safety of his community.</p>
<p>Some countries like Africa have become numbed to strife including civil wars that they no longer anticipate when it is going to happen again. War has displaced more than twenty five million Africans, most of whom live in evacuation camps, with nary a decent roof to shelter even the children.</p>
<p>Like any other war, Civil war can be deadly and can affect majority of the population especially children who could not fend for themselves. Every civil war carries with it human rights abuses from both military and civilians.</p>
<p>The tragedy resulting from every Civil War the world has known is so encompassing. Take this: four million Sudan residents displaced, more than two million lives lost; more than 70 million people in Ethiopia hungry; add the millions of people suffering in Somalia and Ethiopia. This is the face of civil war and every person has to prepare for such an eventuality.</p>
<p>Every family should create an emergency plan no matter what emergency should arise. They should not rely on their governments if they do not want to suffer separation, suffering and death in the government-designated evacuation camps.</p>
<p>Families should consider taking survival courses which may include self defense lessons as well as gun firing lessons. Gun firing can be a family affair although children should be cautioned against the dangers of using guns in ordinary circumstances.</p>
<p>A family would b e better off preparing an emergency first aid kit which should contain the basic medicine for ordinary illnesses. However, a family should from special illnesses like diabetes or asthma and include the basic lie saving and maintenance medicines in the safety kit.</p>
<p>People who live in places that are susceptible to civil war and other emergencies should also pack a special kit which should contain sturdy shoes for family members, maps, all-purpose knife or a Swiss Knife would be better, canned goods, and basic toiletries like soap.</p>
<p>Take every important thing but take only the basic necessities because when a civil war erupts, there may be a chance that the family would be displaced and may b e forced to survive for weeks or even months on the road escaping violence.</p>
<p>Preparing for the eventuality of a civil war is not like courting danger or wishing for it to happen. Rather, it is making sure that the family increases its survival rate when such event happens. It is always better to be prepared for any emergency and if it does not happen at all, then who cares of the family has spent hundreds or perhaps even thousands for the emergency kit. It is all well worth it.</p>